import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Typewriter from "typewriter-effect";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className="homeText">
                    Simple web development for
                    <Typewriter
                        onInit={(typewriter) => {
                            typewriter
                                .typeString("Restaurants")
                                .pauseFor(1500)
                                .deleteAll()
                                .typeString("Gyms")
                                .pauseFor(1500)
                                .deleteAll()
                                .typeString("Aerospace companies")
                                .pauseFor(1500)
                                .deleteAll()
                                .typeString("Law firms")
                                .start();
                        }}
                    />
                </h1>
                {/* <h1 className={styles.title}>Moonwish Studios</h1> */}
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
}
